name: pubspec_checker
description: A simple Dart package that checks the compatibility of all dependencies in the pubspec.yaml file for specified platforms
version: 1.0.4
repository: https://github.com/marianz-bonfire/pubspec_checker
homepage: https://github.com/marianz-bonfire/pubspec_checker
issue_tracker: https://github.com/marianz-bonfire/pubspec_checker/issues

environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  args: ^2.4.1
  http: ^0.13.5
  yaml: ^3.1.1

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  macos:
  web:
  windows:
  linux: